/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yazılım_lab_1;

import java.awt.Color;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;


//KULLANILAN DEĞİŞKENLER VE TANIMLARI
public class Userpanel extends javax.swing.JFrame {
    String[][] kitaplar=new String[23][7];
    vt_baglanti baglanti=new vt_baglanti();
    Pearson p=new Pearson();
    
     Object data[]=new Object[8];
    int b=0;
    int a=0;
    String now_id;
    Hatalar hata=new Hatalar();
   
    
     DefaultTableModel model2;
    // CONSTRUCTOR LOGİN YAPILAN İD Yİ STRİNG OALRAK ALIR  ARAYÜZÜ İNİTİALİZE EDER İLK GİRİLDİĞİNDE KİTAPLARI LİSTELER VE TABLOYA YAZAR GEREKLİ YERLERİ 
     // UNVİSİBLE EDER 
    public Userpanel(String id) {
        now_id=id;
        
        
        initComponents();
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model2=model;
        jLabel3.setVisible(false);
         jPanel3.setVisible(false);
         jPanel4.setVisible(false);
         tabloya_yaz(a);
    
    }
    //KİTAP RESMİNİN URLSİNİ PARAMETRE OLARAK ALIR İMAGE E DÖNÜŞTÜRÜR İMAGE İ İSE İCONA ATAR VE JLABELDA SET EDER
    void url_resim_to_icon(String hedef_url) throws IOException{
        jLabel3.setIcon(null);
        BufferedImage image=null;
        ImageIcon icon;
        
        
        try {
            URL url =new URL(hedef_url);
            image=ImageIO.read(url);
            Image dimg=image.getScaledInstance(380,500,Image.SCALE_DEFAULT); // resmin boyutları ayarlanır
            icon=new ImageIcon(dimg);
            jLabel3.setIcon(icon);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Userpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    //KİTAPLAR TABLOSUNA YAZILACAKLARI VERİTABANINDAN ÇEKER VE TABLOYA YAZAR PARAMETRE OLARAK ALDIĞI SAYI SAYFALAMA İÇİN KULLANILIR SAYFALAMA LIMIT ANAHTAR
    //SÖZCÜĞÜ İLE VERİ TABANINDA YAPILIR SAYI HANGİ İNDEXTEN SONRA ALINACAĞINI BELİRTİR HER ÇAĞIRILDIĞINDA ARRAYLİSTİ VE TABLOYU SIFIRLAR
    void tabloya_yaz(int bos_sayi){
    baglanti.set1.clear();
       model2.setRowCount(0);
        String sorgu="Select * from books2 LIMIT "+bos_sayi+","+23;
        int i=0;
      baglanti.kitap_listele(sorgu);
              while(i<baglanti.set1.size()){
            
        data[0]=baglanti.set1.get(i++);
        data[1]=baglanti.set1.get(i++);
        data[2]=baglanti.set1.get(i++);
        data[3]=baglanti.set1.get(i++);
        data[4]=baglanti.set1.get(i++);
        data[5]=baglanti.set1.get(i++);
        data[6]=baglanti.set1.get(i++);
        data[7]=baglanti.set1.get(i++);
           
           
        model2.addRow(data);
      
        } 
    }
  
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yazılım_lab_1/Pics&Icons/icons8_Shutdown_36px.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1300, 10, 50, 40);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yazılım_lab_1/Pics&Icons/Alta al.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1240, 30, 50, 30);

        jButton3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yazılım_lab_1/Pics&Icons/icons8_Back_32px_1.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(20, 710, 90, 40);

        jButton8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton8.setText("Popular");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusPainted(false);
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(150, 20, 106, 41);

        jButton9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton9.setText("Top 10");
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(270, 20, 106, 41);

        jButton10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton10.setText("New");
        jButton10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setFocusPainted(false);
        jButton10.setFocusable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(390, 20, 106, 41);

        jButton11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton11.setText("My Books");
        jButton11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setFocusPainted(false);
        jButton11.setFocusable(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(510, 20, 106, 41);

        jButton12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton12.setText("All Books");
        jButton12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setFocusPainted(false);
        jButton12.setFocusable(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(30, 20, 106, 41);

        jPanel4.setOpaque(false);

        jTable2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Year", "Publisher", "Rated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setOpaque(false);
        jTable2.setRequestFocusEnabled(false);
        jTable2.setRowHeight(20);
        jTable2.setUpdateSelectionOnSort(false);
        jTable2.setVerifyInputWhenFocusTarget(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yazılım_lab_1/Pics&Icons/icons8_PDF_32px.png"))); // NOI18N
        jButton13.setText("Read");
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setFocusPainted(false);
        jButton13.setFocusable(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(10, 90, 800, 610);

        jPanel3.setOpaque(false);

        jSlider1.setBackground(new java.awt.Color(51, 51, 51));
        jSlider1.setForeground(new java.awt.Color(0, 0, 0));
        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMaximum(10);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(0);
        jSlider1.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Rating :");

        jButton7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yazılım_lab_1/Pics&Icons/icons8_Star_32px.png"))); // NOI18N
        jButton7.setText("Rate");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton7MouseReleased(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(870, 630, 430, 70);

        jPanel2.setOpaque(false);

        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(870, 90, 380, 500);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jTable1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Year", "Publisher"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setRequestFocusEnabled(false);
        jTable1.setRowHeight(20);
        jTable1.setUpdateSelectionOnSort(false);
        jTable1.setVerifyInputWhenFocusTarget(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 800, 499);

        jButton4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yazılım_lab_1/Pics&Icons/icons8_Left_32px.png"))); // NOI18N
        jButton4.setText("Prev");
        jButton4.setToolTipText("");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(12, 547, 106, 41);

        jButton5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yazılım_lab_1/Pics&Icons/icons8_Right_32px.png"))); // NOI18N
        jButton5.setText("Next");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(682, 547, 106, 41);

        jButton6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yazılım_lab_1/Pics&Icons/icons8_PDF_32px.png"))); // NOI18N
        jButton6.setText("Read");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(338, 547, 106, 41);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 90, 800, 610);

        jButton14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton14.setText("Recommended");
        jButton14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setFocusPainted(false);
        jButton14.setFocusable(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(630, 20, 120, 41);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yazılım_lab_1/Pics&Icons/background-with-books-Download-Royalty-free-Vector-File-EPS-161943.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ---------------------------------------------------------- KAPAT VE ALTA AL TUŞLARI --------------------------------------------------------------------
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setExtendedState(HIDE_ON_CLOSE);
    }//GEN-LAST:event_jButton2ActionPerformed
    //---------------------------------------------------------------------------------------------------------------------------------------------------------
    // ------------------------------------------------------------------ GERİ TUŞU -----------------------------------------------------------------------
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        new Gui().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    //--------------------------------------------------------------------------------------------------------------------------------------------------------
    //---------------------------------------------------- GERİ TUŞUNUN RENK AYARI --------------------------------------------------------------------------
    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        jButton3.setForeground(Color.GRAY);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
       jButton3.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton3MouseExited

    
    //KİTAP TABLOSUNUN NEXT TUŞU KAÇ TANE BOŞ OKUNACAĞINI GÖSTERİR SAYFALAMA İÇİN GEREKLİ
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         a=a+23;
        if(a==b)
            a=0;
        
        baglanti.set1.clear();
        System.out.println(a);
        tabloya_yaz(a);
       
    }//GEN-LAST:event_jButton5ActionPerformed

//KİTAP TABLOSUNDA TIKLANAN SATIRIN RESMİNİN URL SİNİ URL TO RESİM METODUNA GÖNDERİR ÇİFT TIKLANDIĞINDA RATE KISMINI VERİ TABANINDAN ÇEKER VE GETİRİR
    // URL Yİ ARRAYLİSTTEN ÇEKER
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jLabel3.setVisible(true);
        jPanel3.setVisible(false);
       String url=baglanti.set1.get((jTable1.getSelectedRow()+1)*8-1).toString();
        //System.out.println(url);
        
        try {
            url_resim_to_icon(url);
            
            
        } catch (IOException ex) {
            Logger.getLogger(Userpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        //OYLAMA İÇİN VE GÖRMEK İÇİN ÇİFT TIKLA
        if(evt.getClickCount()==2){
             JTable target = (JTable)evt.getSource();
             int row = target.getSelectedRow();
             jPanel3.setVisible(true);
             rate_getir();    
        }
    }//GEN-LAST:event_jTable1MouseClicked

    // TABLOYA ÇİFT TIKLANDIĞINDA KİTABIN OYUNU GETİREN METODLAR BİRİNCİ TABLO VE İKİNCİ TABLO İÇİN AYRI AYRI VE JSLİDER A OYU YAZAR
    
    void rate_getir(){
     a=baglanti.avg_rate("select avg(rate) from ratings where isbn="+"'"+jTable1.getValueAt(jTable1.getSelectedRow(),0)+"'");
     System.out.println("select avg(rate) from ratings where isbn="+"'"+jTable1.getValueAt(jTable1.getSelectedRow(),0)+"'");
    jSlider1.setValue(a);
}
void rate_getir2(){
     a=baglanti.avg_rate("select avg(rate) from ratings where isbn="+"'"+jTable2.getValueAt(jTable2.getSelectedRow(),0)+"'");
     System.out.println("select avg(rate) from ratings where isbn="+"'"+jTable2.getValueAt(jTable2.getSelectedRow(),0)+"'");
    jSlider1.setValue(a);
}
// LABEL A BASILDIĞINDA TABLODA SEÇİLİ LANLAR TEMİZLENİR VE RESİM İLE RATE KISMI GİZLENİR
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        jTable1.clearSelection();
        jLabel3.setVisible(false);
        jPanel3.setVisible(false);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    //KİTAP TABLOSUNUN PREV KISMI VERİTABNINDAN ALINAN BİLGİLERİ TUTAN ARRAY LİSTİ SIFIRLAR BOŞ OKUNACAK SAYIYI SET EDER VE TABLO YAZ METODUNU ÇAĞIIRIR
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        a=a-23;
        if(a<0){
            a=baglanti.avg_rate("Select Count(isbn) from books2");
            b=a;
            a=a-23;
        }
        baglanti.set1.clear();
        tabloya_yaz(a);
    }//GEN-LAST:event_jButton4ActionPerformed

    // RATE TUŞU VERİLEN OYU RATİNG DATABASE İNE YAZAR JTABLE1 VE JTABLE2 İÇİN AYRI AYRI HANGİSİ O AN KULLANIMDAYSA O KOD ÇALIŞIR EĞER DAHA ÖNCE
    // KİTAP OYLANMIŞŞSA AYNI KULLANICI TARAFINDAN UPDATE SORGUSU EĞER OYLANMAMIŞSA İNSERT SORGUSU OLUŞTURULUR VE VERİTABANINA YAZILIR
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
          String sorgu=null;
          
      

   if(jTable1.isShowing()){
       if(baglanti.avg_rate("select count(isbn) from ratings where user_id="+"'"+now_id+"' and isbn="+"'"+jTable1.getValueAt(jTable1.getSelectedRow(),0)+"'")==1)
        sorgu="update ratings set rate= "+jSlider1.getValue()+" where user_id="+"'"+now_id+"' and isbn="+"'"+jTable1.getValueAt(jTable1.getSelectedRow(),0)+"'"; 
       else
        sorgu="insert into ratings values("+now_id+",'"+jTable1.getValueAt(jTable1.getSelectedRow(),0)+"',"+jSlider1.getValue()+")";
        }
        
   else if(jTable2.isShowing()){
            if(baglanti.avg_rate("select count(isbn) from ratings where user_id="+"'"+now_id+"' and isbn="+"'"+jTable2.getValueAt(jTable2.getSelectedRow(),0)+"'")==1)
               sorgu="update ratings set rate= "+jSlider1.getValue()+" where user_id="+"'"+now_id+"' and isbn="+"'"+jTable2.getValueAt(jTable2.getSelectedRow(),0)+"'";
            else    
                sorgu="insert into ratings values("+now_id+",'"+jTable2.getValueAt(jTable2.getSelectedRow(),0)+"',"+jSlider1.getValue()+")";
        }
        System.out.println(sorgu);
        new vt_baglanti().user_sil(sorgu);
        
    }//GEN-LAST:event_jButton7ActionPerformed
 
//READ TUŞU KULLANICININ 10 KİTAP OYLAMIŞMI KONTROLÜNÜ YAPAR VE KİTABI AÇAR
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     int oylanan_kitaplar=baglanti.avg_rate("Select count(user_id) from ratings where user_id="+"'"+now_id+"'");
       System.out.println("Select count(user_id) from ratings where user_id="+"'"+now_id+"'");   
       if(oylanan_kitaplar<10){
           hata.hata_yazi_yaz("Rated Books: "+oylanan_kitaplar+ " You Must Rate Atleast 10 Books");
           hata.hata_goster(); 
       }else{
         switch(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString().charAt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString().length()-1)){
             case '1':
                 new denemeee("Books/01.pdf");
                 break;
             case '2':
                 new denemeee("Books/02.pdf");
                 break;
             case '3':
                 new denemeee("Books/03.pdf");
                 break;
             case '4':
                 new denemeee("Books/04.pdf");
                 break;
             case '5':
                 new denemeee("Books/05.pdf");
                 break;
             default:
                 new denemeee("Books/best.pdf");
                 break;
         }
       }
    }//GEN-LAST:event_jButton6ActionPerformed

//POPULAR KİTAPLAR SEKMESİ BU SEKMEYE AİT TABLO VE PANEL AÇILIR DAHA SONRA BOOKS2 TABLOSUNDAN KİTAP BİLGİLERİ VE RATİNGS TABLOSUNDAN EN ÇOK TEKRAR EDEN 
    // KİTAPLARIN İSBN VE TEKRAR SAILARI İNNERJOİN İLE İSBNLER ÜZERİNDEN BİRLEŞİTİRİLEREK OYLANMA SAYILARINA GÖRE SIRALANIR BU SORGU ÇALIŞTIRILARAK 
    // TABLOYA YAZILIR
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
jPanel4.setVisible(true);
jPanel1.setVisible(false);
        DefaultTableModel model3=(DefaultTableModel) jTable2.getModel();

       jButton4.setVisible(false);
       jButton5.setVisible(false);
       baglanti.set1.clear();
       model3.setRowCount(0);
       

        String sorgu="SELECT books2.isbn,title,author,year,publisher,rated.c,images,imagel\n" +
"FROM books2\n" +
"   INNER JOIN (SELECT isbn,count(*) c FROM ratings GROUP BY isbn HAVING COUNT(*) > 1 order by COUNT(*) desc limit 0,23 ) rated\n" +
"           ON books2.isbn = rated.isbn\n" +
"           order by rated.c desc";

           System.out.println(sorgu);
        int j=0;
      baglanti.kitap_listele(sorgu);
              while(j<baglanti.set1.size()){
            
        data[0]=baglanti.set1.get(j++);
        data[1]=baglanti.set1.get(j++);
        data[2]=baglanti.set1.get(j++);
        data[3]=baglanti.set1.get(j++);
        data[4]=baglanti.set1.get(j++);
        data[5]=baglanti.set1.get(j++);
        data[6]=baglanti.set1.get(j++);
        data[7]=baglanti.set1.get(j++);
           
           
        model3.addRow(data);
      
        } 
       
         
    }//GEN-LAST:event_jButton8ActionPerformed

    // EN YENİ 5 KİTAP SEKMESİ ADMİN İN EKLEDİĞİ KİTAPLAR EN ALTTA SIRALANIR YİNE LIMIT ANAHTAR KELİMESİ İLE KİTAP SAYISI VT INDAN ÇEKİLİR VE 5 EKSİĞİ
    // LİMİTE PARAMETRE OLARAK VERİLİR
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      jLabel3.setVisible(false);
      jPanel3.setVisible(false);
      jPanel4.setVisible(false);
      jPanel1.setVisible(true);
      jButton4.setVisible(false);
      jButton5.setVisible(false);
       baglanti.set1.clear();
       model2.setRowCount(0);
        int sayi=baglanti.avg_rate("select count(isbn) from books2")-5;
        String sorgu="select * from books2 limit "+sayi+','+5;
        System.out.println(sorgu);
        int j=0;
      baglanti.kitap_listele(sorgu);
              while(j<baglanti.set1.size()){
            
        data[0]=baglanti.set1.get(j++);
        data[1]=baglanti.set1.get(j++);
        data[2]=baglanti.set1.get(j++);
        data[3]=baglanti.set1.get(j++);
        data[4]=baglanti.set1.get(j++);
        data[5]=baglanti.set1.get(j++);
        data[6]=baglanti.set1.get(j++);
        data[7]=baglanti.set1.get(j++);
        model2.addRow(data);
      
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed

    // KULLANICININ OYLADIĞI KİTAPLAR MYBOOKS SEKMESİNDE GÖSTERİLİR ÖNCE RATİNGS TABLOSUNDAN KULLANICNIN OYLADIĞI KİTAPLARIN İSBNSİ ÇEKİLİR VE İN 
    //ANAHTAR KELİMESİ İLE BOOKS2 TABLOSUNDAN BU KİTAPLAR ÇEKİLİR
    
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
jButton4.setVisible(false);
      jButton5.setVisible(false);
      jPanel4.setVisible(false);
      jPanel1.setVisible(true);
        jLabel3.setVisible(false);
jPanel3.setVisible(false);
       baglanti.set1.clear();
       model2.setRowCount(0);

        String sorgu="Select * from books2 where isbn in (select isbn from ratings where user_id="+"'"+now_id+"')";

           System.out.println(sorgu);
        int j=0;
      baglanti.kitap_listele(sorgu);
              while(j<baglanti.set1.size()){
            
        data[0]=baglanti.set1.get(j++);
        data[1]=baglanti.set1.get(j++);
        data[2]=baglanti.set1.get(j++);
        data[3]=baglanti.set1.get(j++);
        data[4]=baglanti.set1.get(j++);
        data[5]=baglanti.set1.get(j++);
        data[6]=baglanti.set1.get(j++);
        data[7]=baglanti.set1.get(j++);
           
           
        model2.addRow(data);
      
        } 
    }//GEN-LAST:event_jButton11ActionPerformed

    // ALL BOOKS SEKMESİ BÜTÜN KİTAPLARI EN BAŞTAN GETİRİR
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jLabel3.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel1.setVisible(true);
        tabloya_yaz(0);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        
    }//GEN-LAST:event_jButton12ActionPerformed

    // READ BUTONU KULLANICNIN OKUDUĞU KİTAP SAYISI KONTROL EDİLİR  EĞER 10 KİTAP OYLAMIŞSA KİTABI AÇAR
    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int oylanan_kitaplar=baglanti.avg_rate("Select count(user_id) from ratings where user_id="+"'"+now_id+"'");
       System.out.println("Select count(user_id) from ratings where user_id="+"'"+now_id+"'");   
       if(oylanan_kitaplar<10){
           hata.hata_yazi_yaz("Rated Books: "+oylanan_kitaplar+ " You Must Rate Atleast 10 Books");
           hata.hata_goster(); 
       }else{
           //Kitabı aç
       }
    }//GEN-LAST:event_jButton13ActionPerformed

    // POPÜLER KİTAPLAR SEKMESİNDEKİ TABLONUN RESİM VE RATE KISMI
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
         jLabel3.setVisible(true);
        jPanel3.setVisible(false);
       String url=baglanti.set1.get((jTable2.getSelectedRow()+1)*8-1).toString();
        System.out.println(url);
        
        try {
            url_resim_to_icon(url);
            
        } catch (IOException ex) {
            Logger.getLogger(Userpanel.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        //OYLAMA İÇİN VE GÖRMEK İÇİN ÇİFT TIKLA
        if(evt.getClickCount()==2){
             JTable target = (JTable)evt.getSource();
             int row = target.getSelectedRow();
             jPanel3.setVisible(true);
             rate_getir2();
            
            
        }
    }//GEN-LAST:event_jTable2MouseClicked

// EN İYİ KİTAPLAR SEKMESİ YİNE VERİTABANINDA İKİ TABLO BİRLEŞTİRİLEREK VERİLER ÇEKİLİR VE TABLOYA YAZILIR
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jPanel4.setVisible(true);
jPanel1.setVisible(false);
        DefaultTableModel model3=(DefaultTableModel) jTable2.getModel();

       jButton4.setVisible(false);
       jButton5.setVisible(false);
       baglanti.set1.clear();
       model3.setRowCount(0);
       

        String sorgu="SELECT books2.isbn,title,author,year,publisher,rated.c,images,imagel\n" +
"FROM books2\n" +
" INNER JOIN (SELECT isbn,avg(rate) c,count(isbn) d FROM ratings  GROUP BY isbn having d>1 order by c desc,d desc limit 0,1250 ) rated\n" +
"           ON books2.isbn = rated.isbn\n" +
"        order by rated.c desc , rated.d desc";

           System.out.println(sorgu);
        int j=0;
      baglanti.kitap_listele(sorgu);
              while(j<baglanti.set1.size()){
            
        data[0]=baglanti.set1.get(j++);
        data[1]=baglanti.set1.get(j++);
        data[2]=baglanti.set1.get(j++);
        data[3]=baglanti.set1.get(j++);
        data[4]=baglanti.set1.get(j++);
        data[5]=baglanti.set1.get(j++);
        data[6]=baglanti.set1.get(j++);
        data[7]=baglanti.set1.get(j++);
           
           
        model3.addRow(data);
      
        } 
    }//GEN-LAST:event_jButton9ActionPerformed

    //ÖNERİ SEKMESİ KULLANICI CEK VE RATE CEK FONKSİYONLARI ÇAĞIRILIR VE PEARSON KATSAYISLARI HESAPLANARAK HER KULLANICI İÇİN DİZİYE ATILIR VE O DİZİDEN TEK TEK ÇEKİLEREK KULLANICININ
    // ANA KULLANICININ OKUDUĞU KİTAPLARDAN FARKLI VE KULLANICININ 5 VE ÜSTÜ OY VERDİĞİ KİTAPLARI GETİRİR VE TABLOYA YAZAR
    
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
p.t=0;
        jPanel4.setVisible(false);
jPanel1.setVisible(true);
        int oylanan_kitaplar=baglanti.avg_rate("Select count(user_id) from ratings where user_id="+"'"+now_id+"'");
        if(oylanan_kitaplar<10){
            jButton14.setEnabled(false);
            hata.hata_yazi_yaz("You must rate 10 books");
            hata.hata_goster();
            jButton14.setEnabled(true);
        }
        else{
        String sorgu=null;
       baglanti.set1.clear();
        p.kullanici_cek(Integer.parseInt(now_id));
       p.kullanici_rate_cek(Integer.parseInt(now_id));
       model2.setRowCount(0);
       
       for(int i=0;i<p.t;i++){
           
           System.out.println(p.pearsons[i][0]+"="+p.pearsons[i][1]);
           sorgu="select * from books2 where isbn in (select isbn from ratings where user_id='"+p.pearsons[i][0]+"' and isbn  not in(Select isbn from ratings where user_id='"+now_id+"') and rate>5 order by rate desc) limit 0,23";
           System.out.println(sorgu);
           baglanti.kitap_listele(sorgu);
       }
        int j=0;
      
              while(j<baglanti.set1.size()){
            
        data[0]=baglanti.set1.get(j++);
        data[1]=baglanti.set1.get(j++);
        data[2]=baglanti.set1.get(j++);
        data[3]=baglanti.set1.get(j++);
        data[4]=baglanti.set1.get(j++);
        data[5]=baglanti.set1.get(j++);
        data[6]=baglanti.set1.get(j++);
        data[7]=baglanti.set1.get(j++);
           
           
        model2.addRow(data);
      // kitapları doğru sıralamıyor yani ilk önce rate i 10 olanları getirmiyor
        } 
    }
       
       
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
       jButton7.setForeground(Color.GREEN);
    }//GEN-LAST:event_jButton7MousePressed

    private void jButton7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseReleased
       jButton7.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButton7MouseReleased
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userpanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userpanel("160201039").setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}


